name: Schedule Corn

on:
  schedule:
    - cron: '* */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          ref: dev
          persist-credentials: false
          fetch-depth: 1

      - name: npm install
        run: npm install

      - name: generate readme
        run: npm run build
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy to GitHub
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: output
          commit_message: 'Updated by GitHub Actions'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
